# Generated by Django 5.1.7 on 2025-03-29 23:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('string_instruments', 'String Instruments'), ('key_instruments', 'Key Instruments'), ('percussion', 'Percussion'), ('wind_instruments', 'Wind Instruments'), ('speakers_and_studio_equipment', 'Speakers And Studio Equipment'), ('other', 'Other')], max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
