# Generated by Django 5.1.7 on 2025-04-09 12:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, max_length=1000, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='category-icons/'),
        ),
    ]
